import { TEAM_LOGOS } from "./brand";
import {
  DEFAULT_BASE_PRICE,
  SLOT_COUNT,
  TEAM_POINTS,
  type Player,
  type Team,
} from "./types";

export const TEAM_DEFINITIONS = [
  {
    id: "t1",
    name: "Karthigai FC",
    shortName: "KFC",
    color: "#c41e3a",
    logo: TEAM_LOGOS.kfc,
  },
  {
    id: "t2",
    name: "Lightning Stars SC",
    shortName: "LSS",
    color: "#f5c518",
    logo: TEAM_LOGOS.lss,
  },
  {
    id: "t3",
    name: "Delta Super Kings",
    shortName: "DSK",
    color: "#1e40af",
    logo: TEAM_LOGOS.dsk,
  },
  {
    id: "t4",
    name: "Koththiyal Kings Sports Club",
    shortName: "KKSC",
    color: "#15803d",
    logo: TEAM_LOGOS.kksc,
  },
  {
    id: "t5",
    name: "S.K.K UNITED FC",
    shortName: "SKK",
    color: "#1e3a5f",
    logo: TEAM_LOGOS.skk,
  },
] as const;

export function createInitialTeams(): Team[] {
  return TEAM_DEFINITIONS.map((team) => ({
    ...team,
    points: TEAM_POINTS,
    players: Array.from({ length: SLOT_COUNT }, () => null),
  }));
}

/** Official roster: Player ID, name, team representative. IDs 46 and 81 are unused. */
const PLAYER_ROSTER: { id: number; name: string; teamRep: string }[] = [
  { id: 1, name: "Sudharasan", teamRep: "Valvai" },
  { id: 2, name: "SS Kumaran", teamRep: "Valvai" },
  { id: 3, name: "R. Vivekan", teamRep: "Valvai" },
  { id: 4, name: "M. Thamil Venthan", teamRep: "Valvai" },
  { id: 5, name: "A. Neerujan", teamRep: "NYSC" },
  { id: 6, name: "Thanusan", teamRep: "Valvai" },
  { id: 7, name: "Krishnalakshan", teamRep: "NYSC" },
  { id: 8, name: "Arun", teamRep: "Valvai" },
  { id: 9, name: "Anparasan", teamRep: "Valvai" },
  { id: 10, name: "Mayoran", teamRep: "Valvai" },
  { id: 11, name: "Alex", teamRep: "Valvai" },
  { id: 12, name: "M. Abishek", teamRep: "Valvai" },
  { id: 13, name: "U. Thirukumaran", teamRep: "NYSC" },
  { id: 14, name: "S. Pirabakaran", teamRep: "NYSC" },
  { id: 15, name: "P. Kabilraj", teamRep: "Valvai" },
  { id: 16, name: "Roshan", teamRep: "Valvai" },
  { id: 17, name: "T. Jeyam", teamRep: "Valvai" },
  { id: 18, name: "Ranjith", teamRep: "NYSC" },
  { id: 19, name: "Pratheep", teamRep: "Valvai" },
  { id: 20, name: "Kopi", teamRep: "Valvai" },
  { id: 21, name: "J. Kumaran", teamRep: "Valvai" },
  { id: 22, name: "M. Vinothan", teamRep: "NYSC" },
  { id: 23, name: "Bavinthan", teamRep: "Valvai" },
  { id: 24, name: "Vimal", teamRep: "Valvai" },
  { id: 25, name: "R. Abarajithan", teamRep: "Valvai" },
  { id: 26, name: "Kavichelvan", teamRep: "Valvai" },
  { id: 27, name: "Suren", teamRep: "Valvai" },
  { id: 28, name: "S. Vinoth", teamRep: "Valvai" },
  { id: 29, name: "Gowtham", teamRep: "Valvai" },
  { id: 30, name: "Krishnamenan", teamRep: "Valvai" },
  { id: 31, name: "J. Abinaash", teamRep: "Valvai" },
  { id: 32, name: "S. Sharan", teamRep: "NYSC" },
  { id: 33, name: "Rajasukanthan", teamRep: "Valvai" },
  { id: 34, name: "Sarujan", teamRep: "Valvai" },
  { id: 35, name: "Kalainilavan", teamRep: "NYSC" },
  { id: 36, name: "Ranjan", teamRep: "Valvai" },
  { id: 37, name: "V. Piranavan", teamRep: "Valvai" },
  { id: 38, name: "Rishikaran", teamRep: "NYSC" },
  { id: 39, name: "Murukavel", teamRep: "Valvai" },
  { id: 40, name: "Ravi", teamRep: "Valvai" },
  { id: 41, name: "Anpalakan", teamRep: "Valvai" },
  { id: 42, name: "Kirushanth", teamRep: "Valvai" },
  { id: 43, name: "Pirasanth", teamRep: "Valvai" },
  { id: 44, name: "Siva Jivinthan", teamRep: "Valvai" },
  { id: 45, name: "Sajanthan", teamRep: "Valvai" },
  { id: 47, name: "Mayooran", teamRep: "Valvai" },
  { id: 48, name: "Kaneshvaran", teamRep: "Valvai" },
  { id: 49, name: "P. Abishan", teamRep: "NYSC" },
  { id: 50, name: "G. Vasanth", teamRep: "Valvai" },
  { id: 51, name: "S. Kisokumar", teamRep: "Valvai" },
  { id: 52, name: "Suren", teamRep: "Valvai" },
  { id: 53, name: "Aathi", teamRep: "Valvai" },
  { id: 54, name: "Vithulan", teamRep: "Valvai" },
  { id: 55, name: "Sujan", teamRep: "Valvai" },
  { id: 56, name: "T. Kabilan", teamRep: "Valvai" },
  { id: 57, name: "M. Pinkalan", teamRep: "Valvai" },
  { id: 58, name: "R. Sasikumar", teamRep: "Valvai" },
  { id: 59, name: "Santhosh", teamRep: "Valvai" },
  { id: 60, name: "Ranjith", teamRep: "Valvai" },
  { id: 61, name: "Pirasanth", teamRep: "Valvai" },
  { id: 62, name: "Theeparaj", teamRep: "NYSC" },
  { id: 63, name: "Uthi", teamRep: "Valvai" },
  { id: 64, name: "Ranjith", teamRep: "Valvai" },
  { id: 65, name: "Pavi", teamRep: "Valvai" },
  { id: 66, name: "Kabilan", teamRep: "Valvai" },
  { id: 67, name: "Kajan", teamRep: "Valvai" },
  { id: 68, name: "Srisanjeevan", teamRep: "Valvai" },
  { id: 69, name: "Aravind", teamRep: "Valvai" },
  { id: 70, name: "Danusan", teamRep: "NYSC" },
  { id: 71, name: "T. Sivagnanam", teamRep: "Valvai" },
  { id: 72, name: "R. Manimaran", teamRep: "Valvai" },
  { id: 73, name: "R. Pirahalathan", teamRep: "Valvai" },
  { id: 74, name: "N. Nirojan", teamRep: "NYSC" },
  { id: 75, name: "Mukilan", teamRep: "NYSC" },
  { id: 76, name: "Athavan", teamRep: "Valvai" },
  { id: 77, name: "Kapilraj", teamRep: "Valvai" },
  { id: 78, name: "Mayooran", teamRep: "Valvai" },
  { id: 79, name: "Lambotharan", teamRep: "NYSC" },
  { id: 80, name: "A. Kirubakaran", teamRep: "NYSC" },
  { id: 82, name: "Uthayasooriyan", teamRep: "Valvai" },
  { id: 83, name: "Kalayarasan", teamRep: "Valvai" },
  { id: 84, name: "Rajenthiran", teamRep: "Valvai" },
  { id: 85, name: "Cowtham", teamRep: "NYSC" },
  { id: 86, name: "I. Kaviyalan", teamRep: "NYSC" },
  { id: 87, name: "Theepan", teamRep: "Valvai" },
  { id: 88, name: "Prakalathan", teamRep: "Valvai" },
  { id: 89, name: "T. Jeyakanth", teamRep: "Valvai" },
  { id: 90, name: "S. Guruparan", teamRep: "Valvai" },
  { id: 91, name: "Sinthujan", teamRep: "Valvai" },
  { id: 92, name: "Tharun", teamRep: "Valvai" },
  { id: 93, name: "Neerujan", teamRep: "Valvai" },
  { id: 94, name: "S. Vinoban", teamRep: "Valvai" },
  { id: 95, name: "Mugunthan", teamRep: "Valvai" },
  { id: 96, name: "Disok", teamRep: "NYSC" },
  { id: 97, name: "Vino", teamRep: "Valvai" },
  { id: 98, name: "Ulagarasa", teamRep: "Valvai" },
  { id: 99, name: "Sinthujan", teamRep: "NYSC" },
  { id: 100, name: "Inkaran", teamRep: "Valvai" },
  { id: 101, name: "Pakee", teamRep: "NYSC" },
  { id: 102, name: "Naveen", teamRep: "Valvai" },
  { id: 103, name: "Pirayalan", teamRep: "Valvai" },
  { id: 104, name: "Y. Pirathap", teamRep: "NYSC" },
  { id: 105, name: "S. Dinushan", teamRep: "Valvai" },
  { id: 106, name: "Kajenthiran", teamRep: "NYSC" },
  { id: 107, name: "Pirakash", teamRep: "Valvai" },
  { id: 108, name: "Pirakas", teamRep: "NYSC" },
  { id: 109, name: "Sulaksan", teamRep: "NYSC" },
  { id: 110, name: "Ramanan", teamRep: "Valvai" },
  { id: 111, name: "Nichan", teamRep: "NYSC" },
  { id: 112, name: "P. Vijendran", teamRep: "Valvai" },
  { id: 113, name: "Kalatharan", teamRep: "Valvai" },
  { id: 114, name: "Theepan", teamRep: "Valvai" },
  { id: 115, name: "Sivarupan", teamRep: "Valvai" },
  { id: 116, name: "Kinist", teamRep: "Valvai" },
  { id: 117, name: "S.Santhosh", teamRep: "Valvai" },
];

export const AVAILABLE_PLAYERS: Player[] = PLAYER_ROSTER.map((entry) => ({
  id: `p${entry.id}`,
  name: entry.name,
  role: "Footballer",
  playerNo: `No. ${String(entry.id).padStart(2, "0")}`,
  contact: "",
  designation: entry.teamRep,
  photo: "",
  basePrice: DEFAULT_BASE_PRICE,
}));
